---

snipeit_app_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32393938646137383130646338306130323133386161326261333038646165353131336662396564
          6163666231623535633336633866316337663361333366370a303731323935663232353663653437
          63316231373065633161356438643630643236663333363938633635326330353333376131393962
          6462346664366631620a393137386638653435336464643535376330646432663234333232303930
          32626337646638626537626231646531666134333639326564613136326537373436626537663463
          36313035323938393961306333643063376636366666383437313635393133376331346564393531
          383061353833353665346362383835346537
snipeit_db_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30653764363532613137653563303334303735343036363739666530343036616137626638616135
          3334323661316437666235613635626430653630323462380a376536633534326366643237326138
          36633332336235393438386261643632376264336636616334313032313431613036353161383039
          3361323062363438340a623363356361333566326666376464656337376133363132316638653466
          6339
snipeit_mysql_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36326433386534633465383239666634313466366133343236346638613462353865353564333431
          3137623031613164636664636263326134316435633433620a613862363433393030393931643535
          63653632636363386362363931333137316430313234633565323366313263383562336631383962
          3432623665306634310a303361383565656534316564343939636263396139396139653265376436
          6633
snipeit_mail_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34333862393863666238396662313664613431616433303231616636323937363137376565623065
          6131323432653933326535633632356331383966373532610a323333666534383562626332393132
          65393234376333346463636333303236363339633132383438316532613237313336303039333237
          3962663332353837350a396662363564666530636236323431323733666166623734633566666364
          3633
