---
- name: Run docker-compose # noqa: no-changed-when
  community.docker.docker_compose_v2:
    project_src: /etc/freifunk/
    pull: always
    recreate: always
    remove_orphans: true
    wait: true

# vim: set filetype=yaml:
