---
buildbot_worker_name: akira-home
buildbot_worker_pwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30393433623335303735613338373662303938653663646538386561363964646633346464323630
          3063306265346139363963396162643966383832353864660a356631333664363232633962356635
          33396532633538326538333461636537393332666464663639633064636639653730333138636430
          3130323561663931650a343730396665343336663336306662346137643432373165303739383035
          32343737636135386530333462653631333266326238343964383439343938323233633165316136
          36643036626466633666373863346364666466313534353632646633336635333735646262306666
          396463343061613935336238346462373761

buildbot_worker_contact: Martin <martin.hubner uff web ponkt de>
buildbot_worker_info: VM with 4 Cores, 4GB RAM
...
