---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: restarted
  when: not ansible_check_mode

- name: Restart prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: true
    state: restarted
  when: not ansible_check_mode

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    enabled: true
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd:
    daemon_reload: true
    name: postfix
    enabled: true
    state: restarted
