---
- name: Restart rsyncd
  ansible.builtin.systemd:
    name: rsync
    state: restarted
    enabled: true

- name: Reload iptables # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    - iptables-restore /etc/iptables/rules.v4
    - ip6tables-restore /etc/iptables/rules.v6
