---
- name: Install composer dependencies # noqa: no-changed-when
  ansible.builtin.command:
    cmd: composer install --no-dev --optimize-autoloader
    chdir: "{{ ff_wiki_basedir }}/wwwroot/"
  become: true
  become_user: caddy
